---
apiVersion: v1
kind: Service
metadata:
  name: identityprovider2
  labels:
    app: identityprovider2-deployment
spec:
  type: ClusterIP
  selector:
    app: identityprovider2-deployment
  ports:
    - name: https
      port: 443
      targetPort: https
